parameters:
#    keboola_db_writer.example.class: Keboola\DbWriterBundle\Example

services:
#    keboola_db_writer.example:
#        class: %keboola_db_writer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
