services:
    wr_db.configuration_factory:
        class: Keboola\DbWriterBundle\Writer\ConfigurationFactory
        arguments: [%app_name%]

    wr_db.writer_factory:
        class: Keboola\DbWriterBundle\Writer\WriterFactory
        arguments: [@logger]

    wr_db.job_executor:
        class: Keboola\DbWriterBundle\Job\Executor
        arguments: [@wr_db.configuration_factory, @wr_db.writer_factory, @logger, @syrup.temp]
